resources:
# All RBAC will be applied under this service account in
# the deployment namespace. You may comment out this resource
# if your manager will use a service account that exists at
# runtime. Be sure to update RoleBinding and ClusterRoleBinding
# subjects if changing service account names.
- service_account.yaml
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
# The following RBAC configurations are used to protect
# the metrics endpoint with authn/authz. These configurations
# ensure that only authorized users and service accounts
# can access the metrics endpoint. Comment the following
# permissions if you want to disable this protection.
# More info: https://book.kubebuilder.io/reference/metrics.html
- metrics_auth_role.yaml
- metrics_auth_role_binding.yaml
- metrics_reader_role.yaml
# For each CRD, "Admin", "Editor" and "Viewer" roles are scaffolded by
# default, aiding admins in cluster management. Those roles are
# not used by the pxc-anonymizer itself. You can comment the following lines
# if you do not want those helpers be installed with your Project.
- bootstrap_admin_role.yaml
- bootstrap_editor_role.yaml
- bootstrap_viewer_role.yaml
- anonymizationschedule_admin_role.yaml
- anonymizationschedule_editor_role.yaml
- anonymizationschedule_viewer_role.yaml
- anonymizationrun_admin_role.yaml
- anonymizationrun_editor_role.yaml
- anonymizationrun_viewer_role.yaml
- anonymizationpolicy_admin_role.yaml
- anonymizationpolicy_editor_role.yaml
- anonymizationpolicy_viewer_role.yaml
- backuppointer_admin_role.yaml
- backuppointer_editor_role.yaml
- backuppointer_viewer_role.yaml
