---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - pxc-anonymizer.io
  resources:
  - anonymizationpolicies
  - anonymizationruns
  - anonymizationschedules
  - backuppointers
  - bootstraps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pxc-anonymizer.io
  resources:
  - anonymizationpolicies/finalizers
  - anonymizationruns/finalizers
  - anonymizationschedules/finalizers
  - backuppointers/finalizers
  - bootstraps/finalizers
  verbs:
  - update
- apiGroups:
  - pxc-anonymizer.io
  resources:
  - anonymizationpolicies/status
  - anonymizationruns/status
  - anonymizationschedules/status
  - backuppointers/status
  - bootstraps/status
  verbs:
  - get
  - patch
  - update
