apiVersion: pxc-anonymizer.io/v1alpha1
kind: AnonymizationSchedule
metadata:
  labels:
    app.kubernetes.io/name: pxc-anonymizer
    app.kubernetes.io/managed-by: kustomize
  name: anonymizationschedule-sample
spec:
  # TODO(user): Add fields here
