apiVersion: pxc-anonymizer.io/v1alpha1
kind: AnonymizationPolicy
metadata:
  labels:
    app.kubernetes.io/name: pxc-anonymizer
    app.kubernetes.io/managed-by: kustomize
  name: anonymizationpolicy-sample
spec:
  # TODO(user): Add fields here
