//go:build !ignore_autogenerated

/*
Copyright 2026 pxc-anonymizer contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymizationPolicy) DeepCopyInto(out *AnonymizationPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymizationPolicy.
func (in *AnonymizationPolicy) DeepCopy() *AnonymizationPolicy {
	if in == nil {
		return nil
	}
	out := new(AnonymizationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnonymizationPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymizationPolicyList) DeepCopyInto(out *AnonymizationPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AnonymizationPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymizationPolicyList.
func (in *AnonymizationPolicyList) DeepCopy() *AnonymizationPolicyList {
	if in == nil {
		return nil
	}
	out := new(AnonymizationPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnonymizationPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymizationPolicySpec) DeepCopyInto(out *AnonymizationPolicySpec) {
	*out = *in
	in.Determinism.DeepCopyInto(&out.Determinism)
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = new(PolicyDefaults)
		**out = **in
	}
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]SQLStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Databases != nil {
		in, out := &in.Databases, &out.Databases
		*out = make([]DatabasePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymizationPolicySpec.
func (in *AnonymizationPolicySpec) DeepCopy() *AnonymizationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AnonymizationPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymizationPolicyStatus) DeepCopyInto(out *AnonymizationPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymizationPolicyStatus.
func (in *AnonymizationPolicyStatus) DeepCopy() *AnonymizationPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AnonymizationPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymizationRun) DeepCopyInto(out *AnonymizationRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymizationRun.
func (in *AnonymizationRun) DeepCopy() *AnonymizationRun {
	if in == nil {
		return nil
	}
	out := new(AnonymizationRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnonymizationRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymizationRunList) DeepCopyInto(out *AnonymizationRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AnonymizationRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymizationRunList.
func (in *AnonymizationRunList) DeepCopy() *AnonymizationRunList {
	if in == nil {
		return nil
	}
	out := new(AnonymizationRunList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnonymizationRunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymizationRunSpec) DeepCopyInto(out *AnonymizationRunSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	out.PolicyRef = in.PolicyRef
	in.TempCluster.DeepCopyInto(&out.TempCluster)
	in.Output.DeepCopyInto(&out.Output)
	in.Runner.DeepCopyInto(&out.Runner)
	out.Timeouts = in.Timeouts
	out.Cleanup = in.Cleanup
	if in.TTLSecondsAfterFinished != nil {
		in, out := &in.TTLSecondsAfterFinished, &out.TTLSecondsAfterFinished
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymizationRunSpec.
func (in *AnonymizationRunSpec) DeepCopy() *AnonymizationRunSpec {
	if in == nil {
		return nil
	}
	out := new(AnonymizationRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymizationRunStatus) DeepCopyInto(out *AnonymizationRunStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(ResolvedSource)
		(*in).DeepCopyInto(*out)
	}
	if in.TempCluster != nil {
		in, out := &in.TempCluster, &out.TempCluster
		*out = new(TempClusterStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Anonymize != nil {
		in, out := &in.Anonymize, &out.Anonymize
		*out = new(AnonymizeStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(PublishedBackup)
		(*in).DeepCopyInto(*out)
	}
	if in.PrunedBackups != nil {
		in, out := &in.PrunedBackups, &out.PrunedBackups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymizationRunStatus.
func (in *AnonymizationRunStatus) DeepCopy() *AnonymizationRunStatus {
	if in == nil {
		return nil
	}
	out := new(AnonymizationRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymizationRunTemplate) DeepCopyInto(out *AnonymizationRunTemplate) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymizationRunTemplate.
func (in *AnonymizationRunTemplate) DeepCopy() *AnonymizationRunTemplate {
	if in == nil {
		return nil
	}
	out := new(AnonymizationRunTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymizationSchedule) DeepCopyInto(out *AnonymizationSchedule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymizationSchedule.
func (in *AnonymizationSchedule) DeepCopy() *AnonymizationSchedule {
	if in == nil {
		return nil
	}
	out := new(AnonymizationSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnonymizationSchedule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymizationScheduleList) DeepCopyInto(out *AnonymizationScheduleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AnonymizationSchedule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymizationScheduleList.
func (in *AnonymizationScheduleList) DeepCopy() *AnonymizationScheduleList {
	if in == nil {
		return nil
	}
	out := new(AnonymizationScheduleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnonymizationScheduleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymizationScheduleSpec) DeepCopyInto(out *AnonymizationScheduleSpec) {
	*out = *in
	if in.TimeZone != nil {
		in, out := &in.TimeZone, &out.TimeZone
		*out = new(string)
		**out = **in
	}
	if in.StartingDeadlineSeconds != nil {
		in, out := &in.StartingDeadlineSeconds, &out.StartingDeadlineSeconds
		*out = new(int64)
		**out = **in
	}
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymizationScheduleSpec.
func (in *AnonymizationScheduleSpec) DeepCopy() *AnonymizationScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(AnonymizationScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymizationScheduleStatus) DeepCopyInto(out *AnonymizationScheduleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastScheduleTime != nil {
		in, out := &in.LastScheduleTime, &out.LastScheduleTime
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessfulTime != nil {
		in, out := &in.LastSuccessfulTime, &out.LastSuccessfulTime
		*out = (*in).DeepCopy()
	}
	if in.NextScheduleTime != nil {
		in, out := &in.NextScheduleTime, &out.NextScheduleTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymizationScheduleStatus.
func (in *AnonymizationScheduleStatus) DeepCopy() *AnonymizationScheduleStatus {
	if in == nil {
		return nil
	}
	out := new(AnonymizationScheduleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymizeProgress) DeepCopyInto(out *AnonymizeProgress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymizeProgress.
func (in *AnonymizeProgress) DeepCopy() *AnonymizeProgress {
	if in == nil {
		return nil
	}
	out := new(AnonymizeProgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymizeResult) DeepCopyInto(out *AnonymizeResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymizeResult.
func (in *AnonymizeResult) DeepCopy() *AnonymizeResult {
	if in == nil {
		return nil
	}
	out := new(AnonymizeResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymizeStatus) DeepCopyInto(out *AnonymizeStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Progress != nil {
		in, out := &in.Progress, &out.Progress
		*out = new(AnonymizeProgress)
		**out = **in
	}
	if in.LastResult != nil {
		in, out := &in.LastResult, &out.LastResult
		*out = new(AnonymizeResult)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymizeStatus.
func (in *AnonymizeStatus) DeepCopy() *AnonymizeStatus {
	if in == nil {
		return nil
	}
	out := new(AnonymizeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupCounts) DeepCopyInto(out *BackupCounts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupCounts.
func (in *BackupCounts) DeepCopy() *BackupCounts {
	if in == nil {
		return nil
	}
	out := new(BackupCounts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupPointer) DeepCopyInto(out *BackupPointer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupPointer.
func (in *BackupPointer) DeepCopy() *BackupPointer {
	if in == nil {
		return nil
	}
	out := new(BackupPointer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupPointer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupPointerList) DeepCopyInto(out *BackupPointerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BackupPointer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupPointerList.
func (in *BackupPointerList) DeepCopy() *BackupPointerList {
	if in == nil {
		return nil
	}
	out := new(BackupPointerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupPointerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupPointerSource) DeepCopyInto(out *BackupPointerSource) {
	*out = *in
	if in.StorageNames != nil {
		in, out := &in.StorageNames, &out.StorageNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupPointerSource.
func (in *BackupPointerSource) DeepCopy() *BackupPointerSource {
	if in == nil {
		return nil
	}
	out := new(BackupPointerSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupPointerSpec) DeepCopyInto(out *BackupPointerSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	in.Target.DeepCopyInto(&out.Target)
	if in.StaleAfter != nil {
		in, out := &in.StaleAfter, &out.StaleAfter
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.VerifyInterval != nil {
		in, out := &in.VerifyInterval, &out.VerifyInterval
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupPointerSpec.
func (in *BackupPointerSpec) DeepCopy() *BackupPointerSpec {
	if in == nil {
		return nil
	}
	out := new(BackupPointerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupPointerStatus) DeepCopyInto(out *BackupPointerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Current != nil {
		in, out := &in.Current, &out.Current
		*out = new(PublishedBackup)
		(*in).DeepCopyInto(*out)
	}
	if in.Previous != nil {
		in, out := &in.Previous, &out.Previous
		*out = new(PublishedBackup)
		(*in).DeepCopyInto(*out)
	}
	out.Backups = in.Backups
	if in.NextVerifyTime != nil {
		in, out := &in.NextVerifyTime, &out.NextVerifyTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupPointerStatus.
func (in *BackupPointerStatus) DeepCopy() *BackupPointerStatus {
	if in == nil {
		return nil
	}
	out := new(BackupPointerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Bootstrap) DeepCopyInto(out *Bootstrap) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Bootstrap.
func (in *Bootstrap) DeepCopy() *Bootstrap {
	if in == nil {
		return nil
	}
	out := new(Bootstrap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Bootstrap) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapExecutionStatus) DeepCopyInto(out *BootstrapExecutionStatus) {
	*out = *in
	if in.Selected != nil {
		in, out := &in.Selected, &out.Selected
		*out = make([]CrossplaneObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]BootstrapTargetExecution, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapExecutionStatus.
func (in *BootstrapExecutionStatus) DeepCopy() *BootstrapExecutionStatus {
	if in == nil {
		return nil
	}
	out := new(BootstrapExecutionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapList) DeepCopyInto(out *BootstrapList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Bootstrap, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapList.
func (in *BootstrapList) DeepCopy() *BootstrapList {
	if in == nil {
		return nil
	}
	out := new(BootstrapList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BootstrapList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapRunRecord) DeepCopyInto(out *BootstrapRunRecord) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapRunRecord.
func (in *BootstrapRunRecord) DeepCopy() *BootstrapRunRecord {
	if in == nil {
		return nil
	}
	out := new(BootstrapRunRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapSource) DeepCopyInto(out *BootstrapSource) {
	*out = *in
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(HTTPPointerSource)
		(*in).DeepCopyInto(*out)
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3PointerSource)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxAge != nil {
		in, out := &in.MaxAge, &out.MaxAge
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapSource.
func (in *BootstrapSource) DeepCopy() *BootstrapSource {
	if in == nil {
		return nil
	}
	out := new(BootstrapSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapSpec) DeepCopyInto(out *BootstrapSpec) {
	*out = *in
	in.Pointer.DeepCopyInto(&out.Pointer)
	in.Restore.DeepCopyInto(&out.Restore)
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]BootstrapTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Crossplane != nil {
		in, out := &in.Crossplane, &out.Crossplane
		*out = new(CrossplaneSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Timeouts.DeepCopyInto(&out.Timeouts)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapSpec.
func (in *BootstrapSpec) DeepCopy() *BootstrapSpec {
	if in == nil {
		return nil
	}
	out := new(BootstrapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapStatus) DeepCopyInto(out *BootstrapStatus) {
	*out = *in
	if in.Execution != nil {
		in, out := &in.Execution, &out.Execution
		*out = new(BootstrapExecutionStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(ResolvedSource)
		(*in).DeepCopyInto(*out)
	}
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]BootstrapTargetStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Crossplane != nil {
		in, out := &in.Crossplane, &out.Crossplane
		*out = new(CrossplaneStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.History != nil {
		in, out := &in.History, &out.History
		*out = make([]BootstrapRunRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapStatus.
func (in *BootstrapStatus) DeepCopy() *BootstrapStatus {
	if in == nil {
		return nil
	}
	out := new(BootstrapStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapTarget) DeepCopyInto(out *BootstrapTarget) {
	*out = *in
	if in.ContainerOptions != nil {
		in, out := &in.ContainerOptions, &out.ContainerOptions
		*out = new(XtrabackupContainerOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.Restore != nil {
		in, out := &in.Restore, &out.Restore
		*out = new(RestoreS3Credentials)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapTarget.
func (in *BootstrapTarget) DeepCopy() *BootstrapTarget {
	if in == nil {
		return nil
	}
	out := new(BootstrapTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapTargetExecution) DeepCopyInto(out *BootstrapTargetExecution) {
	*out = *in
	in.Restore.DeepCopyInto(&out.Restore)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapTargetExecution.
func (in *BootstrapTargetExecution) DeepCopy() *BootstrapTargetExecution {
	if in == nil {
		return nil
	}
	out := new(BootstrapTargetExecution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapTargetStatus) DeepCopyInto(out *BootstrapTargetStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapTargetStatus.
func (in *BootstrapTargetStatus) DeepCopy() *BootstrapTargetStatus {
	if in == nil {
		return nil
	}
	out := new(BootstrapTargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapTimeouts) DeepCopyInto(out *BootstrapTimeouts) {
	*out = *in
	if in.ClustersReady != nil {
		in, out := &in.ClustersReady, &out.ClustersReady
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Pointer != nil {
		in, out := &in.Pointer, &out.Pointer
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Restore != nil {
		in, out := &in.Restore, &out.Restore
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Crossplane != nil {
		in, out := &in.Crossplane, &out.Crossplane
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapTimeouts.
func (in *BootstrapTimeouts) DeepCopy() *BootstrapTimeouts {
	if in == nil {
		return nil
	}
	out := new(BootstrapTimeouts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CleanupSpec) DeepCopyInto(out *CleanupSpec) {
	*out = *in
	out.HoldTempClusterFor = in.HoldTempClusterFor
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CleanupSpec.
func (in *CleanupSpec) DeepCopy() *CleanupSpec {
	if in == nil {
		return nil
	}
	out := new(CleanupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ColumnRule) DeepCopyInto(out *ColumnRule) {
	*out = *in
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = new(StrategyParams)
		(*in).DeepCopyInto(*out)
	}
	if in.Consistent != nil {
		in, out := &in.Consistent, &out.Consistent
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ColumnRule.
func (in *ColumnRule) DeepCopy() *ColumnRule {
	if in == nil {
		return nil
	}
	out := new(ColumnRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrossplaneObjectReference) DeepCopyInto(out *CrossplaneObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrossplaneObjectReference.
func (in *CrossplaneObjectReference) DeepCopy() *CrossplaneObjectReference {
	if in == nil {
		return nil
	}
	out := new(CrossplaneObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrossplaneRecreate) DeepCopyInto(out *CrossplaneRecreate) {
	*out = *in
	if in.Kinds != nil {
		in, out := &in.Kinds, &out.Kinds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WaitForRecreation != nil {
		in, out := &in.WaitForRecreation, &out.WaitForRecreation
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrossplaneRecreate.
func (in *CrossplaneRecreate) DeepCopy() *CrossplaneRecreate {
	if in == nil {
		return nil
	}
	out := new(CrossplaneRecreate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrossplaneRecreation) DeepCopyInto(out *CrossplaneRecreation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrossplaneRecreation.
func (in *CrossplaneRecreation) DeepCopy() *CrossplaneRecreation {
	if in == nil {
		return nil
	}
	out := new(CrossplaneRecreation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrossplaneSpec) DeepCopyInto(out *CrossplaneSpec) {
	*out = *in
	if in.Kinds != nil {
		in, out := &in.Kinds, &out.Kinds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Pause != nil {
		in, out := &in.Pause, &out.Pause
		*out = new(bool)
		**out = **in
	}
	if in.Resume != nil {
		in, out := &in.Resume, &out.Resume
		*out = new(bool)
		**out = **in
	}
	if in.Recreate != nil {
		in, out := &in.Recreate, &out.Recreate
		*out = new(CrossplaneRecreate)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadinessTimeout != nil {
		in, out := &in.ReadinessTimeout, &out.ReadinessTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrossplaneSpec.
func (in *CrossplaneSpec) DeepCopy() *CrossplaneSpec {
	if in == nil {
		return nil
	}
	out := new(CrossplaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrossplaneStatus) DeepCopyInto(out *CrossplaneStatus) {
	*out = *in
	if in.Paused != nil {
		in, out := &in.Paused, &out.Paused
		*out = make([]CrossplaneObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Resumed != nil {
		in, out := &in.Resumed, &out.Resumed
		*out = make([]CrossplaneObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Recreated != nil {
		in, out := &in.Recreated, &out.Recreated
		*out = make([]CrossplaneObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Pending != nil {
		in, out := &in.Pending, &out.Pending
		*out = make([]CrossplaneObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Recreating != nil {
		in, out := &in.Recreating, &out.Recreating
		*out = make([]CrossplaneRecreation, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrossplaneStatus.
func (in *CrossplaneStatus) DeepCopy() *CrossplaneStatus {
	if in == nil {
		return nil
	}
	out := new(CrossplaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabasePolicy) DeepCopyInto(out *DatabasePolicy) {
	*out = *in
	if in.Pre != nil {
		in, out := &in.Pre, &out.Pre
		*out = make([]StepRef, len(*in))
		copy(*out, *in)
	}
	if in.Post != nil {
		in, out := &in.Post, &out.Post
		*out = make([]StepRef, len(*in))
		copy(*out, *in)
	}
	if in.Tables != nil {
		in, out := &in.Tables, &out.Tables
		*out = make([]TablePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabasePolicy.
func (in *DatabasePolicy) DeepCopy() *DatabasePolicy {
	if in == nil {
		return nil
	}
	out := new(DatabasePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeterminismSpec) DeepCopyInto(out *DeterminismSpec) {
	*out = *in
	if in.SeedSecretRef != nil {
		in, out := &in.SeedSecretRef, &out.SeedSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeterminismSpec.
func (in *DeterminismSpec) DeepCopy() *DeterminismSpec {
	if in == nil {
		return nil
	}
	out := new(DeterminismSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPPointerSource) DeepCopyInto(out *HTTPPointerSource) {
	*out = *in
	if in.CASecretRef != nil {
		in, out := &in.CASecretRef, &out.CASecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPPointerSource.
func (in *HTTPPointerSource) DeepCopy() *HTTPPointerSource {
	if in == nil {
		return nil
	}
	out := new(HTTPPointerSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IgnoreSpec) DeepCopyInto(out *IgnoreSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IgnoreSpec.
func (in *IgnoreSpec) DeepCopy() *IgnoreSpec {
	if in == nil {
		return nil
	}
	out := new(IgnoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStorageSecretKeys) DeepCopyInto(out *ObjectStorageSecretKeys) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStorageSecretKeys.
func (in *ObjectStorageSecretKeys) DeepCopy() *ObjectStorageSecretKeys {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageSecretKeys)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStorageSpec) DeepCopyInto(out *ObjectStorageSpec) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = new(ObjectStorageSecretKeys)
		**out = **in
	}
	if in.PathStyle != nil {
		in, out := &in.PathStyle, &out.PathStyle
		*out = new(bool)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(ObjectStorageTLS)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStorageSpec.
func (in *ObjectStorageSpec) DeepCopy() *ObjectStorageSpec {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStorageTLS) DeepCopyInto(out *ObjectStorageTLS) {
	*out = *in
	if in.CASecretRef != nil {
		in, out := &in.CASecretRef, &out.CASecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStorageTLS.
func (in *ObjectStorageTLS) DeepCopy() *ObjectStorageTLS {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutputRetention) DeepCopyInto(out *OutputRetention) {
	*out = *in
	out.DeleteFailedAfter = in.DeleteFailedAfter
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutputRetention.
func (in *OutputRetention) DeepCopy() *OutputRetention {
	if in == nil {
		return nil
	}
	out := new(OutputRetention)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutputSpec) DeepCopyInto(out *OutputSpec) {
	*out = *in
	in.ObjectStorage.DeepCopyInto(&out.ObjectStorage)
	if in.ContainerOptions != nil {
		in, out := &in.ContainerOptions, &out.ContainerOptions
		*out = new(XtrabackupContainerOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.Pointer != nil {
		in, out := &in.Pointer, &out.Pointer
		*out = new(PointerTarget)
		(*in).DeepCopyInto(*out)
	}
	out.Retention = in.Retention
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutputSpec.
func (in *OutputSpec) DeepCopy() *OutputSpec {
	if in == nil {
		return nil
	}
	out := new(OutputSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PointerSource) DeepCopyInto(out *PointerSource) {
	*out = *in
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(HTTPPointerSource)
		(*in).DeepCopyInto(*out)
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3PointerSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PointerSource.
func (in *PointerSource) DeepCopy() *PointerSource {
	if in == nil {
		return nil
	}
	out := new(PointerSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PointerTarget) DeepCopyInto(out *PointerTarget) {
	*out = *in
	in.ObjectStorage.DeepCopyInto(&out.ObjectStorage)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PointerTarget.
func (in *PointerTarget) DeepCopy() *PointerTarget {
	if in == nil {
		return nil
	}
	out := new(PointerTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyDefaults) DeepCopyInto(out *PolicyDefaults) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyDefaults.
func (in *PolicyDefaults) DeepCopy() *PolicyDefaults {
	if in == nil {
		return nil
	}
	out := new(PolicyDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublishedBackup) DeepCopyInto(out *PublishedBackup) {
	*out = *in
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.PublishedAt != nil {
		in, out := &in.PublishedAt, &out.PublishedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublishedBackup.
func (in *PublishedBackup) DeepCopy() *PublishedBackup {
	if in == nil {
		return nil
	}
	out := new(PublishedBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedSource) DeepCopyInto(out *ResolvedSource) {
	*out = *in
	if in.PointerPublishedAt != nil {
		in, out := &in.PointerPublishedAt, &out.PointerPublishedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedSource.
func (in *ResolvedSource) DeepCopy() *ResolvedSource {
	if in == nil {
		return nil
	}
	out := new(ResolvedSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreS3Credentials) DeepCopyInto(out *RestoreS3Credentials) {
	*out = *in
	if in.VerifyTLS != nil {
		in, out := &in.VerifyTLS, &out.VerifyTLS
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreS3Credentials.
func (in *RestoreS3Credentials) DeepCopy() *RestoreS3Credentials {
	if in == nil {
		return nil
	}
	out := new(RestoreS3Credentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunSource) DeepCopyInto(out *RunSource) {
	*out = *in
	if in.BackupPointerRef != nil {
		in, out := &in.BackupPointerRef, &out.BackupPointerRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.Pointer != nil {
		in, out := &in.Pointer, &out.Pointer
		*out = new(PointerSource)
		(*in).DeepCopyInto(*out)
	}
	if in.BackupRef != nil {
		in, out := &in.BackupRef, &out.BackupRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	in.Restore.DeepCopyInto(&out.Restore)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunSource.
func (in *RunSource) DeepCopy() *RunSource {
	if in == nil {
		return nil
	}
	out := new(RunSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunTemplateMetadata) DeepCopyInto(out *RunTemplateMetadata) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunTemplateMetadata.
func (in *RunTemplateMetadata) DeepCopy() *RunTemplateMetadata {
	if in == nil {
		return nil
	}
	out := new(RunTemplateMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunTimeouts) DeepCopyInto(out *RunTimeouts) {
	*out = *in
	out.ClusterReady = in.ClusterReady
	out.Restore = in.Restore
	out.Anonymize = in.Anonymize
	out.Backup = in.Backup
	out.Publish = in.Publish
	out.Cleanup = in.Cleanup
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunTimeouts.
func (in *RunTimeouts) DeepCopy() *RunTimeouts {
	if in == nil {
		return nil
	}
	out := new(RunTimeouts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerPodSpec) DeepCopyInto(out *RunnerPodSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerPodSpec.
func (in *RunnerPodSpec) DeepCopy() *RunnerPodSpec {
	if in == nil {
		return nil
	}
	out := new(RunnerPodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerSpec) DeepCopyInto(out *RunnerSpec) {
	*out = *in
	in.RunnerPodSpec.DeepCopyInto(&out.RunnerPodSpec)
	if in.PageSize != nil {
		in, out := &in.PageSize, &out.PageSize
		*out = new(int32)
		**out = **in
	}
	if in.DisableBinlog != nil {
		in, out := &in.DisableBinlog, &out.DisableBinlog
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerSpec.
func (in *RunnerSpec) DeepCopy() *RunnerSpec {
	if in == nil {
		return nil
	}
	out := new(RunnerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3PointerSource) DeepCopyInto(out *S3PointerSource) {
	*out = *in
	in.ObjectStorage.DeepCopyInto(&out.ObjectStorage)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3PointerSource.
func (in *S3PointerSource) DeepCopy() *S3PointerSource {
	if in == nil {
		return nil
	}
	out := new(S3PointerSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SQLStep) DeepCopyInto(out *SQLStep) {
	*out = *in
	if in.ConfigMapKeyRef != nil {
		in, out := &in.ConfigMapKeyRef, &out.ConfigMapKeyRef
		*out = new(v1.ConfigMapKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SQLStep.
func (in *SQLStep) DeepCopy() *SQLStep {
	if in == nil {
		return nil
	}
	out := new(SQLStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepRef) DeepCopyInto(out *StepRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepRef.
func (in *StepRef) DeepCopy() *StepRef {
	if in == nil {
		return nil
	}
	out := new(StepRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StrategyParams) DeepCopyInto(out *StrategyParams) {
	*out = *in
	if in.ASCII != nil {
		in, out := &in.ASCII, &out.ASCII
		*out = new(bool)
		**out = **in
	}
	if in.Digits != nil {
		in, out := &in.Digits, &out.Digits
		*out = new(int32)
		**out = **in
	}
	if in.Length != nil {
		in, out := &in.Length, &out.Length
		*out = new(int32)
		**out = **in
	}
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(int64)
		**out = **in
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(int64)
		**out = **in
	}
	if in.MaxLength != nil {
		in, out := &in.MaxLength, &out.MaxLength
		*out = new(int32)
		**out = **in
	}
	if in.Sentences != nil {
		in, out := &in.Sentences, &out.Sentences
		*out = new(int32)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.ValueFrom != nil {
		in, out := &in.ValueFrom, &out.ValueFrom
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.KeepPrefix != nil {
		in, out := &in.KeepPrefix, &out.KeepPrefix
		*out = new(int32)
		**out = **in
	}
	if in.KeepSuffix != nil {
		in, out := &in.KeepSuffix, &out.KeepSuffix
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StrategyParams.
func (in *StrategyParams) DeepCopy() *StrategyParams {
	if in == nil {
		return nil
	}
	out := new(StrategyParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TablePolicy) DeepCopyInto(out *TablePolicy) {
	*out = *in
	if in.PrimaryKey != nil {
		in, out := &in.PrimaryKey, &out.PrimaryKey
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Ignore != nil {
		in, out := &in.Ignore, &out.Ignore
		*out = new(IgnoreSpec)
		**out = **in
	}
	if in.Columns != nil {
		in, out := &in.Columns, &out.Columns
		*out = make([]ColumnRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PageSize != nil {
		in, out := &in.PageSize, &out.PageSize
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TablePolicy.
func (in *TablePolicy) DeepCopy() *TablePolicy {
	if in == nil {
		return nil
	}
	out := new(TablePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TempClusterSpec) DeepCopyInto(out *TempClusterSpec) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
	in.Resources.DeepCopyInto(&out.Resources)
	if in.SystemUsersSecretRef != nil {
		in, out := &in.SystemUsersSecretRef, &out.SystemUsersSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.HAProxy != nil {
		in, out := &in.HAProxy, &out.HAProxy
		*out = new(bool)
		**out = **in
	}
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TempClusterSpec.
func (in *TempClusterSpec) DeepCopy() *TempClusterSpec {
	if in == nil {
		return nil
	}
	out := new(TempClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TempClusterStatus) DeepCopyInto(out *TempClusterStatus) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.ReadyAt != nil {
		in, out := &in.ReadyAt, &out.ReadyAt
		*out = (*in).DeepCopy()
	}
	if in.DeletedAt != nil {
		in, out := &in.DeletedAt, &out.DeletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TempClusterStatus.
func (in *TempClusterStatus) DeepCopy() *TempClusterStatus {
	if in == nil {
		return nil
	}
	out := new(TempClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TempClusterStorage) DeepCopyInto(out *TempClusterStorage) {
	*out = *in
	out.Size = in.Size.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TempClusterStorage.
func (in *TempClusterStorage) DeepCopy() *TempClusterStorage {
	if in == nil {
		return nil
	}
	out := new(TempClusterStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XtrabackupContainerOptions) DeepCopyInto(out *XtrabackupContainerOptions) {
	*out = *in
	if in.Xbcloud != nil {
		in, out := &in.Xbcloud, &out.Xbcloud
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Xbstream != nil {
		in, out := &in.Xbstream, &out.Xbstream
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Xtrabackup != nil {
		in, out := &in.Xtrabackup, &out.Xtrabackup
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XtrabackupContainerOptions.
func (in *XtrabackupContainerOptions) DeepCopy() *XtrabackupContainerOptions {
	if in == nil {
		return nil
	}
	out := new(XtrabackupContainerOptions)
	in.DeepCopyInto(out)
	return out
}
